services:
  sflow-rt:
    build: ./sflow-rt
    container_name: sflow-rt
    restart: unless-stopped
    # volumes:
    # - ./sflow-rt/store:/sflow-rt/store
    # - ./sflow-rt/app:/sflow-rt/app 
    ports:
      - '6343:6343/udp'
      - '8008:8008'

  
  onos:
    image: onosproject/onos:2.5.1
    container_name: onos
    restart: unless-stopped
    ports:
      - '8181:8181'
      - '8001:8101'
      - '6653:6653'
      - '6640:6640'
  
  
  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb2
    restart: unless-stopped
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb2/data:/var/lib/influxdb2:rw
      # - ./influxdb2/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ADMIN_TOKEN = OaujNLMeQcH3ziNdeP-huuOIdiJPgSwh2nR9mDqwF5tlu5kYQ6RO1KzCdr8lBShb_w0vGwxxWoZulLIojIEd3w==
      - INFLUXDB_ORG=ibn
      - INFLUXDB_BUCKET=ibn
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=admin
      - INFLUXDB_INIT_PASSWORD=admin123
      - INFLUXDB_INIT_ORG=ibn
      - INFLUXDB_INIT_BUCKET=ibn
      - INFLUXDB_INIT_ADMIN_TOKEN = OaujNLMeQcH3ziNdeP-huuOIdiJPgSwh2nR9mDqwF5tlu5kYQ6RO1KzCdr8lBShb_w0vGwxxWoZulLIojIEd3w==
